(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
(require 'init-melpa)
(require 'init-async)
(require 'init-themes)
(require 'init-smex)
(require 'init-semantic)
(require 'init-company)
(require 'init-helm)
(require 'init-cc-mode)
(require 'init-flycheck)
(require 'init-smartparens)
(require 'init-projectile)
(require 'init-yasnippet)
(require 'init-magit)
(require 'init-ui)
(require 'init-go)

(setq tramp-default-method "ssh")
(setq tab-width 4)
(setq scroll-preserve-screen-position t)
